### PR TITLE
Exploring Lua-based data structures/functions

### PR DESCRIPTION
**Pull request by gucci-on-fleek**
> [!IMPORTANT]  
> This PR is **not** intended to be merged. Rather, this is intended as somewhere to discuss Lua-based implementations of some expl3 functions so as to not further derail PR latex3/latex3#1542.

Experimental, Lua-based reimplementations of a few expl3 data structures and functions. 

Potential candidate modules: 

- [x] **l3prop** (partially):
    - ☑ All global, non-branching functions.
    - ☐ Branching functions (`T`/`F` variants).
    - ☑ Local functions:
    - ☐ Additional profiling/performance enhancements.
- [ ] **l3seq** (planned):
    This will be implemented quite similarly to the l3prop tests.
- [ ] **l3fp** (maybe).
    A minimal implementation should be fairly simple, but perfect compatibility is probably impossible due to weird precision issues. The speedup here would likely be fairly large, although floating point code is used rarely enough that I doubt that it would be noticeable in an average document.
- [ ] **l3regex** (maybe):
    There's good potential here for a major speedup, but this one would be _hard_ to implement. I've already written an LPEG-based parser for a subset of TeX (for a project to extract metadata from the TUGboat back issues) which helps a little, but I still suspect that this is beyond what I'm capable of.
- [ ] **l3expan** (maybe):
    With LuaTeX, _everything_ is expandable if you try hard enough. The methods to do this aren't terribly fast themselves, but it means that you can replace a slow expandable macro with a fast non-expandable macro while still keeping it expandable. Not sure if there's any good uses for this though.

### CODE REVIEW

**Comment by gucci-on-fleek** [comment]
### Initial notes

I finally had some time today to take a look at this. ae81fa7 is my first attempt at a Lua-based property list replacement. I only started work on this this afternoon, so the implementation is a little rough around the edges. Some ad-hoc testing seems to suggest that this is a viable method to increase performance; I'm hoping that later revisions will make this even quicker.

To test this, run:

```sh
cd lua-tests/
lualatex prop-test.tex
```

If there's any interest here, I can work on this some more, with the goal of eventually getting this properly integrated into the main expl3 code. And if anyone has any suggestions/comments/criticism, feel free to add a comment or review.

### Next steps
- Add the branching (`T`/`F`) variants.
- Figure out a solution for local property lists.
- More profiling/performance enhancements.
- Implement l3seq.

**Comment by Witiko** [comment]
@gucci-on-fleek I validated the code from this draft PR in PR https://github.com/gucci-on-fleek/latex3/pull/2.

Namely, the PR contains the following items:
1. Changes that you may want to merge into this draft PR
2. Description of how I conducted the validation
3. Description of an issue that affects both correctness and performance and should be fixed before a performance evaluation:

> All tokens in property list keys have catcode 12 (other) in the TeX-based data structures and functions, whereas some tokens have catcode 11 (letter) in the Lua-based data structures and functions:
> 
> > The ⟨key⟩ and ⟨value⟩ may both be given as any balanced text, and the ⟨key⟩ is processed using `\tl_to_str:n`, meaning that category codes are ignored. —[The LaTeX3 Interfaces][1] (LaTeX team, 2024, Chapter 25)
> 
> This affects both correctness and performance:
> - Correctness: TeX-based data functions will look up values based on keys with different catcodes, whereas Lua-based data functions will not.
> - Performance: The backing Lua tables can be directly keyed with Lua strings, which may be faster than the current approach.

After the issue from item 3 has been fixed, I will evaluate the performance.

 [1]: http://mirrors.ctan.org/macros/latex/required/l3kernel/interface3.pdf

**Comment by gucci-on-fleek** [comment]
@Witiko 

Thanks! I've merged #2 in 7a16e7c and _maybe_ fixed (3) in 6f05fe2. I've only looked at this for about 10 minutes though; I should have some time to look at this tomorrow.

Also, I've given you push access to this fork. Go nuts with changes/commits if you want, or just open new PRs if you prefer.

**Comment by gucci-on-fleek** [comment]
@Witiko 

> ### Validation
> 
> In addition to file `prop-test.tex` from PR #1, which I renamed to `lprop-test.tex` in commit [88f77fc](https://github.com/gucci-on-fleek/latex3/commit/88f77fc92a499185e43a1b1b519adc6a4a45f7d1) from this PR, I added file `prop-test.tex`. Both files perform the same operations but whereas file `prop-test.tex` uses the TeX-based data structures and functions from `l3kernel`, `lprop-test.tex` uses the Lua-based data structures and functions from draft PR #1. The file `prop-test.tex` was produced from file `lprop-test.tex` as follows:
> 
> ```shell
> $ sed -e s/lprop/prop/g -e 's/\\file_input:n { lua-prop }/% &/' lua-tests/lprop-test.tex > lua-tests/prop-test.tex
> ```
> 
> Since the file `prop-test.tex` can be produced automatically, I did not add it to the Git repository to prevent unnecessary repetition.
> 
> To validate the Lua-based data structures and functions, I ran the following two commands in the directory `lua-tests/`:
> 
> ```shell
> $ lualatex prop-test.tex
> $ lualatex lprop-test.tex
> ```

Ah, good idea to convert between `lprop` and `prop` automatically like that. I've pushed a change to make it even easier: just run

```sh
$ git diff <(lualatex lprop-test tex) <(lualatex lprop-test lua)
```

Current output:

```diff
diff --git a/dev/fd/63 b/dev/fd/62
--- a/dev/fd/63
+++ b/dev/fd/62
@@ -4,7 +4,7 @@ This is LuaHBTeX, Version 1.18.2 (TeX Live 2025/dev)
 LaTeX2e <2024-06-01> patch level 2
 L3 programming layer <2024-05-27>
  (/usr/local/texlive/2024/texmf-dist/tex/latex/l3experimental/l3benchmark/l3benchmark.sty (/usr/local/texlive/2024/texmf-dist/tex/latex/l3kernel/expl3.sty (/usr/local/texlive/2024/texmf-dist/tex/latex/l3backend/l3backend-luatex.def)))
-
+ (./lua-prop.tex)
 
 === new ===
 
@@ -180,9 +180,9 @@ The token list contains the tokens:
 
 )
 (see the transcript file for additional information)
- 296 words of node memory still in use:
-   1 hlist, 3 kern, 1 glyph, 1 attribute, 39 glue_spec, 1 attribute_list nodes
-   avail lists: 2:11,3:3,4:1,5:7
+ 304 words of node memory still in use:
+   1 hlist, 3 kern, 1 glyph, 2 attribute, 39 glue_spec, 2 attribute_list, 1 user_defined nodes
+   avail lists: 2:9,3:3,5:7
 
 warning  (pdf backend): no pages of output.
 Transcript written on lprop-test.log.
```

Lua iteration order is unstable, so I had to run it a few times until I got lucky, but it looks like the basic functionality is identical between the Lua and expl3 implementations.

> Then, I inspected the logs and I made the following two changes:
> 
>  1. Make signature of `\lprop_gconcat:NNN` the same as `\prop_gconcat:NNN`. Wheras `\prop_gconcat:NNN` has parameters in the order out, first, second, `\lprop_gconcat:NNN` had previously parameters in the order first, second, out. This change was added in commit [686b3d6](https://github.com/gucci-on-fleek/latex3/commit/686b3d6a764afdf441f3c8dda80863ecd7848862) from this PR.
> 
>  2. Do not assume in `lprop-test.tex` that the Lua-based functions `\lprop_item:Nn` and `\lprop_count:N` only require a single expansion. The corresponding TeX-based functions `\prop_item:Nn` and `\prop_count:N` require multiple expansions, which makes `lprop-test.tex` implementation-dependent. This change was added in commit [c9caeb9](https://github.com/gucci-on-fleek/latex3/commit/c9caeb9a83a24a6bc4d35ead8621975938dae6cd) from this PR.

Both fixes look great, thanks!

> The diff indicates that the Lua-based and the TeX-based data structures and functions are indistinguishable by the test except for the following difference: All tokens in property list keys have catcode 12 (other) in the TeX-based data structures and functions, whereas some tokens have catcode 11 (letter) in the Lua-based data structures and functions:
> 
> > The ⟨key⟩ and ⟨value⟩ may both be given as any balanced text, and the ⟨key⟩ is processed using `\tl_to_str:n`, meaning that category codes are ignored. —[The LaTeX3 Interfaces](http://mirrors.ctan.org/macros/latex/required/l3kernel/interface3.pdf) (LaTeX team, 2024, Chapter 25)
> 
> This affects both correctness and performance:
> 
>  * Correctness: TeX-based data functions will look up values based on keys with different catcodes, whereas Lua-based data functions will not.
> 
>  * Performance: The backing Lua tables can be directly keyed with Lua strings, which may be faster than the current approach.

I was already directly using Lua strings as the table keys, the problem was that I was outputting them to `\lprop_map_function:NN` using `tex.sprint(key)`, which converts the key to tokens using the current catcodes. Luckily, there's a builtin flag to disable it, so the fix was [rather simple](https://github.com/gucci-on-fleek/latex3/commit/6f05fe).

> After this difference has been fixed, I will evaluate the performance.

Sounds good, thanks!

I've done a little bit of benchmarking already, and _most_ of the functions seem a little faster, but I've compiled all of my LuaTeX binaries with `-g3 -O0`, so my results aren't very generalizable. I've also mainly tested it with 3-item property lists, but given the overhead of the TeX–Lua interfaces and the asymptotic behaviour of the expl3 implementations, I'd expect the Lua version to look even better with larger lists.

There's also a chance that you'll find that the Lua versions aren't all that much faster, which wouldn't be completely surprising given how well-optimized both TeX and expl3 are.

**Comment by gucci-on-fleek** [comment]
Ok, I've now updated the code to fully-support local property lists. Local property lists are slower than global property lists, but I'm not really sure by how much. If they are much slower, then we'll need to keep the separate code for the local and global lists, but if they're fairly close, then I can merge the two implementations together, which will make maintenance/further development much easier.

**Comment by gucci-on-fleek** [comment]
Ok, a quick test. I've added the below to `expl-lua-test.tex` at the top of the “Property List Tests” section:

```tex
\cs_set_eq:NN \__example_test:nn \use_none:nn
\fp_gset:Nn \g_benchmark_duration_target_fp { 2 }

\__example_section:n { local-1 }
\lprop_new:N \l__example_A_lprop
\benchmark:n {
    \lprop_put:Nnn \l__example_A_lprop { key1 } { value1 }
    \use_none:e { \lprop_item:Nn \l__example_A_lprop { key1 } }
    \use_none:e { \lprop_item:Nn \l__example_A_lprop { key2 } }
    \group_begin:
        \lprop_put:Nnn \l__example_A_lprop { key2 } { value2 }
        \use_none:e { \lprop_item:Nn \l__example_A_lprop { key1 } }
        \use_none:e { \lprop_item:Nn \l__example_A_lprop { key2 } }
    \group_end:
    \use_none:e { \lprop_item:Nn \l__example_A_lprop { key1 } }
    \use_none:e { \lprop_item:Nn \l__example_A_lprop { key2 } }
}

\__example_section:n { global-1 }
\lprop_new:N \g__example_A_lprop
\benchmark:n {
    \lprop_gput:Nnn \g__example_A_lprop { key1 } { value1 }
    \use_none:e { \lprop_item:Nn \g__example_A_lprop { key1 } }
    \use_none:e { \lprop_item:Nn \g__example_A_lprop { key2 } }
    \group_begin:
        \lprop_gput:Nnn \g__example_A_lprop { key2 } { value2 }
        \use_none:e { \lprop_item:Nn \g__example_A_lprop { key1 } }
        \use_none:e { \lprop_item:Nn \g__example_A_lprop { key2 } }
    \group_end:
    \use_none:e { \lprop_item:Nn \g__example_A_lprop { key1 } }
    \use_none:e { \lprop_item:Nn \g__example_A_lprop { key2 } }
}

\__example_section:n { local-2 }
\benchmark:n {
    \cs_undefine:N \l__example_A_lprop
    \lprop_new:N \l__example_A_lprop

    \lprop_put:Nnn \l__example_A_lprop { key1 } { value1 }
    \lprop_map_function:NN \l__example_A_lprop \__example_test:nn
    \group_begin:
        \lprop_remove:Nn \l__example_A_lprop { key1 }
        \lprop_put:Nnn \l__example_A_lprop { key2 } { value2 }
        \lprop_map_function:NN \l__example_A_lprop \__example_test:nn
        \group_begin:
            \lprop_put:Nnn \l__example_A_lprop { key3 } { value3 }
            \lprop_map_function:NN \l__example_A_lprop \__example_test:nn
        \group_end:
        \lprop_map_function:NN \l__example_A_lprop \__example_test:nn
    \group_end:
    \lprop_map_function:NN \l__example_A_lprop \__example_test:nn
}

\__example_section:n { global-2 }
\benchmark:n {
    \cs_undefine:N \g__example_A_lprop
    \lprop_new:N \g__example_A_lprop

    \lprop_gput:Nnn \g__example_A_lprop { key1 } { value1 }
    \lprop_map_function:NN \g__example_A_lprop \__example_test:nn
    \group_begin:
        \lprop_gremove:Nn \g__example_A_lprop { key1 }
        \lprop_gput:Nnn \g__example_A_lprop { key2 } { value2 }
        \lprop_map_function:NN \g__example_A_lprop \__example_test:nn
        \group_begin:
            \lprop_gput:Nnn \g__example_A_lprop { key3 } { value3 }
            \lprop_map_function:NN \g__example_A_lprop \__example_test:nn
        \group_end:
        \lprop_map_function:NN \g__example_A_lprop \__example_test:nn
    \group_end:
    \lprop_map_function:NN \g__example_A_lprop \__example_test:nn
}

\csname @@end\endcsname
```

With `lualatex expl-lua-test tex`, I get
```log
=== prop: local-1 ===
1.36e-4 seconds (346 ops)

=== prop: global-1 ===
1.51e-4 seconds (390 ops)

=== prop: local-2 ===
3.48e-5 seconds (89.4 ops)

=== prop: global-2 ===
3.57e-5 seconds (91.5 ops)
```

and with `lualatex expl-lua-test lua` I get

```log
=== prop: local-1 ===
1.95e-5 seconds (78.8 ops)

=== prop: global-1 ===
1.59e-5 seconds (63.8 ops)

=== prop: local-2 ===
5.51e-5 seconds (221 ops)

=== prop: global-2 ===
4.41e-5 seconds (176 ops)
```

**Comment by gucci-on-fleek** [comment]
Alright, I've added some benchmarking tests in 9a8dc83. I'll mention this again: I've compiled my LuaTeX binaries with `-g3 -O0` (no optimizations and full debug symbols), so these results may not generalize to the average user. 

Anyways, here are the results:

<table>
    <tr>
        <td rowspan="3"></td>
        <th colspan="6" align="center">Kilo-Operations</th>
    </tr>
    <tr>
        <th colspan="3" align="center">Local</th>
        <th colspan="3" align="center">Global</th>
    </tr>
    <tr>
        <th align="right">Flat</th>
        <th align="left">Linked</th>
        <th align="left">Lua</th>
        <th align="left">Flat</th>
        <th align="left">Linked</th>
        <th align="left">Lua</th>
    </tr>
    <tr>
        <th align="right"><code>put-same</code></th>
        <td align="right">1320</td>
        <td align="right">34</td>
        <td align="right">21</td>
        <td align="right">1310</td>
        <td align="right">35</td>
        <td align="right">26</td>
    </tr>
    <tr>
        <th align="right"><code>put-rand</code></th>
        <td align="right">2960</td>
        <td align="right">38</td>
        <td align="right">45</td>
        <td align="right">3000</td>
        <td align="right">39</td>
        <td align="right">46</td>
    </tr>
    <tr>
        <th align="right"><code>get</code></th>
        <td align="right">905</td>
        <td align="right">28</td>
        <td align="right">16</td>
        <td align="right">936</td>
        <td align="right">28</td>
        <td align="right">16</td>
    </tr>
    <tr>
        <th align="right"><code>pop</code></th>
        <td align="right">470</td>
        <td align="right">12</td>
        <td align="right">9</td>
        <td align="right">470</td>
        <td align="right">12</td>
        <td align="right">7</td>
    </tr>
    <tr>
        <th align="right"><code>map</code></th>
        <td align="right">2</td>
        <td align="right">3</td>
        <td align="right">7</td>
        <td align="right">2</td>
        <td align="right">3</td>
        <td align="right">9</td>
    </tr>
    <tr>
        <th align="right"><code>item</code></th>
        <td align="right">1680</td>
        <td align="right">12</td>
        <td align="right">7</td>
        <td align="right">1620</td>
        <td align="right">12</td>
        <td align="right">7</td>
    </tr>
    <tr>
        <th align="right"><code>count</code></th>
        <td align="right">2</td>
        <td align="right">3</td>
        <td align="right">0</td>
        <td align="right">2</td>
        <td align="right">3</td>
        <td align="right">0</td>
    </tr>
    <tr>
        <th align="right"><code>concat</code></th>
        <td align="right">1390</td>
        <td align="right">14</td>
        <td align="right">1</td>
        <td align="right">1330</td>
        <td align="right">14</td>
        <td align="right">1</td>
    </tr>
    <tr>
        <th align="right"><code>clear</code></th>
        <td align="right">0</td>
        <td align="right">0</td>
        <td align="right">0</td>
        <td align="right">0</td>
        <td align="right">0</td>
        <td align="right">0</td>
    </tr>
    <tr>
        <th align="right"><code>keyval</code></th>
        <td align="right">181</td>
        <td align="right">2</td>
        <td align="right">3</td>
        <td align="right">194</td>
        <td align="right">2</td>
        <td align="right">2</td>
    </tr>
    <tr>
        <th align="right"><code>grouping</code></th>
        <td align="right">3830</td>
        <td align="right">16</td>
        <td align="right">10</td>
        <td align="right">9430</td>
        <td align="right">16</td>
        <td align="right">7</td>
    </tr>
    <tr>
        <th align="right"><code>set-eq</code></th>
        <td align="right">0</td>
        <td align="right">2</td>
        <td align="right">0</td>
        <td align="right">0</td>
        <td align="right">2</td>
        <td align="right">0</td>
    </tr>
    <tr>
        <th align="right">Geometric Mean</th>
        <td align="right">46</td>
        <td align="right">5</td>
        <td align="right">2</td>
        <td align="right">50</td>
        <td align="right">5</td>
        <td align="right">1</td>
    </tr>
</table>
<table>
    <tr>
        <td rowspan="3"></td>
        <th colspan="6" align="center">Seconds</th>
    </tr>
    <tr>
        <th colspan="3" align="center">Local</th>
        <th colspan="3" align="center">Global</th>
    </tr>
    <tr>
        <th align="right">Flat</th>
        <th align="left">Linked</th>
        <th align="left">Lua</th>
        <th align="left">Flat</th>
        <th align="left">Linked</th>
        <th align="left">Lua</th>
    </tr>
    <tr>
        <th align="right"><code>put-same</code></th>
        <td align="left">0.3250</td>
        <td align="left">0.0085</td>
        <td align="left">0.0052</td>
        <td align="left">0.3240</td>
        <td align="left">0.0085</td>
        <td align="left">0.0064</td>
    </tr>
    <tr>
        <th align="right"><code>put-rand</code></th>
        <td align="left">0.7290</td>
        <td align="left">0.0094</td>
        <td align="left">0.0111</td>
        <td align="left">0.7400</td>
        <td align="left">0.0095</td>
        <td align="left">0.0114</td>
    </tr>
    <tr>
        <th align="right"><code>get</code></th>
        <td align="left">0.2260</td>
        <td align="left">0.0069</td>
        <td align="left">0.0040</td>
        <td align="left">0.2370</td>
        <td align="left">0.0069</td>
        <td align="left">0.0038</td>
    </tr>
    <tr>
        <th align="right"><code>pop</code></th>
        <td align="left">0.1170</td>
        <td align="left">0.0030</td>
        <td align="left">0.0021</td>
        <td align="left">0.1190</td>
        <td align="left">0.0030</td>
        <td align="left">0.0017</td>
    </tr>
    <tr>
        <th align="right"><code>map</code></th>
        <td align="left">0.00038</td>
        <td align="left">0.00064</td>
        <td align="left">0.00165</td>
        <td align="left">0.00038</td>
        <td align="left">0.00064</td>
        <td align="left">0.00233</td>
    </tr>
    <tr>
        <th align="right"><code>item</code></th>
        <td align="left">0.4180</td>
        <td align="left">0.0029</td>
        <td align="left">0.0018</td>
        <td align="left">0.4020</td>
        <td align="left">0.0029</td>
        <td align="left">0.0016</td>
    </tr>
    <tr>
        <th align="right"><code>count</code></th>
        <td align="left">0.000393</td>
        <td align="left">0.000664</td>
        <td align="left">0.000087</td>
        <td align="left">0.000380</td>
        <td align="left">0.000669</td>
        <td align="left">0.000045</td>
    </tr>
    <tr>
        <th align="right"><code>concat</code></th>
        <td align="left">0.34400</td>
        <td align="left">0.00345</td>
        <td align="left">0.00022</td>
        <td align="left">0.32800</td>
        <td align="left">0.00348</td>
        <td align="left">0.00023</td>
    </tr>
    <tr>
        <th align="right"><code>clear</code></th>
        <td align="left">0.0000010</td>
        <td align="left">0.0000022</td>
        <td align="left">0.0000942</td>
        <td align="left">0.0000011</td>
        <td align="left">0.0000023</td>
        <td align="left">0.0000005</td>
    </tr>
    <tr>
        <th align="right"><code>keyval</code></th>
        <td align="left">0.04470</td>
        <td align="left">0.00057</td>
        <td align="left">0.00062</td>
        <td align="left">0.04780</td>
        <td align="left">0.00057</td>
        <td align="left">0.00061</td>
    </tr>
    <tr>
        <th align="right"><code>grouping</code></th>
        <td align="left">0.9490</td>
        <td align="left">0.0040</td>
        <td align="left">0.0025</td>
        <td align="left">2.5500</td>
        <td align="left">0.0040</td>
        <td align="left">0.0018</td>
    </tr>
    <tr>
        <th align="right"><code>set-eq</code></th>
        <td align="left">0.00000089</td>
        <td align="left">0.00037300</td>
        <td align="left">0.00000003</td>
        <td align="left">0.00000088</td>
        <td align="left">0.00038500</td>
        <td align="left">0.00000038</td>
    </tr>
    <tr>
        <th align="right">Geometric Mean</th>
        <td align="left">0.01148</td>
        <td align="left">0.00124</td>
        <td align="left">0.00047</td>
        <td align="left">0.01253</td>
        <td align="left">0.00125</td>
        <td align="left">0.00035</td>
    </tr>
</table>
<table>
    <tr>
        <td rowspan="3"></td>
        <th colspan="6" align="center">Rank</th>
    </tr>
    <tr>
        <th colspan="3" align="center">Local</th>
        <th colspan="3" align="center">Global</th>
    </tr>
    <tr>
        <th align="right">Flat</th>
        <th align="left">Linked</th>
        <th align="left">Lua</th>
        <th align="left">Flat</th>
        <th align="left">Linked</th>
        <th align="left">Lua</th>
    </tr>
    <tr>
        <th align="right"><code>put-same</code></th>
        <td align="left">6</td>
        <td align="left">3</td>
        <td align="left">1</td>
        <td align="left">5</td>
        <td align="left">4</td>
        <td align="left">2</td>
    </tr>
    <tr>
        <th align="right"><code>put-rand</code></th>
        <td align="left">5</td>
        <td align="left">1</td>
        <td align="left">3</td>
        <td align="left">6</td>
        <td align="left">2</td>
        <td align="left">4</td>
    </tr>
    <tr>
        <th align="right"><code>get</code></th>
        <td align="left">5</td>
        <td align="left">4</td>
        <td align="left">2</td>
        <td align="left">6</td>
        <td align="left">3</td>
        <td align="left">1</td>
    </tr>
    <tr>
        <th align="right"><code>pop</code></th>
        <td align="left">5</td>
        <td align="left">3</td>
        <td align="left">2</td>
        <td align="left">5</td>
        <td align="left">4</td>
        <td align="left">1</td>
    </tr>
    <tr>
        <th align="right"><code>map</code></th>
        <td align="left">1</td>
        <td align="left">3</td>
        <td align="left">5</td>
        <td align="left">2</td>
        <td align="left">3</td>
        <td align="left">6</td>
    </tr>
    <tr>
        <th align="right"><code>item</code></th>
        <td align="left">6</td>
        <td align="left">3</td>
        <td align="left">2</td>
        <td align="left">5</td>
        <td align="left">3</td>
        <td align="left">1</td>
    </tr>
    <tr>
        <th align="right"><code>count</code></th>
        <td align="left">4</td>
        <td align="left">5</td>
        <td align="left">2</td>
        <td align="left">3</td>
        <td align="left">6</td>
        <td align="left">1</td>
    </tr>
    <tr>
        <th align="right"><code>concat</code></th>
        <td align="left">6</td>
        <td align="left">3</td>
        <td align="left">1</td>
        <td align="left">5</td>
        <td align="left">4</td>
        <td align="left">2</td>
    </tr>
    <tr>
        <th align="right"><code>clear</code></th>
        <td align="left">2</td>
        <td align="left">5</td>
        <td align="left">6</td>
        <td align="left">3</td>
        <td align="left">4</td>
        <td align="left">1</td>
    </tr>
    <tr>
        <th align="right"><code>keyval</code></th>
        <td align="left">5</td>
        <td align="left">1</td>
        <td align="left">4</td>
        <td align="left">6</td>
        <td align="left">2</td>
        <td align="left">3</td>
    </tr>
    <tr>
        <th align="right"><code>grouping</code></th>
        <td align="left">5</td>
        <td align="left">4</td>
        <td align="left">2</td>
        <td align="left">6</td>
        <td align="left">3</td>
        <td align="left">1</td>
    </tr>
    <tr>
        <th align="right"><code>set-eq</code></th>
        <td align="left">4</td>
        <td align="left">5</td>
        <td align="left">1</td>
        <td align="left">3</td>
        <td align="left">6</td>
        <td align="left">2</td>
    </tr>
    <tr>
        <th align="right">Arithmetic Mean</th>
        <td align="left">4.5</td>
        <td align="left">3.3</td>
        <td align="left">2.6</td>
        <td align="left">4.6</td>
        <td align="left">3.7</td>
        <td align="left">2.1</td>
    </tr>
</table>

So the Lua implementation appears to be many times faster than the “flat” property lists, and about 50% faster than the “linked” property lists. However, for a few operations the Lua implementation is slower than the the TeX implementations, although generally not by much. Also, the global-only Lua implementation is slightly faster than the version that properly handles grouping, but not by very much, so it's probably safe to use the grouped version for both local and global assignments.

**Comment by gucci-on-fleek** [comment]
I've ran this through a profiler, and it looks like most of the time is being spent in Lua:

[profile](https://tug.org/~mseven/files/expl3-lua-profile.svg)

More specifically, 40% of the total time is being spent in Lua. Drilling into this, 3.0% of the total time is spent in `next` (`pairs`/`ipairs`), 2.0% in the garbage collector, 0.6% checking the current group level, 0.2% in `token.get_mode`, 2.8% in `tex.sprint`, 2.8% in `token.get_next`, 2.2% in `token.scan_csname`, 11.2% in `token.scan_toks`, 1.6% in table indexing, 0.5% in table allocation, 1.0% in token indexing, 2.6% in adding a new key to a table, 0.4% in the length operator `#`, and 9.0% in other Lua stuff. On top of this, there's an extra 12.9% of the total time also spent in Lua. This time is tracked differently, but it's probably safe to just add 10% to all of the above numbers.

It's unclear how closely this would match the numbers with an optimized binary, but given how much time is spent in the `token` module C functions, there's not too much room here to further optimize things from Lua, but I can still think of a few places. I can also see a few places to optimize the C function `run_scan_toks`, although it's likely that the compiler would do lots of this for me if I let it :)

**Comment by gucci-on-fleek** [comment]
Moved to latex3/latex3#1557; please continue discussion there.

**Pull request closed without merging**
